version: 1
global_level: WARNING

features:
  furnace_group_breakdown: true

modules:
  geo: INFO
  pam: INFO
  tm: INFO

function_overrides:
  # Suppress noisy functions
  calculate_unit_production_cost: WARNING
  extract_price_from_costcurve: WARNING
  calculate_variable_opex: WARNING
  calculate_material_total: WARNING
  calculate_energy_total: WARNING
  generate_input_effectiveness_mapping_from_feedstocks: ERROR

external:
  pyomo: ERROR
