version: 1
global_level: WARNING

features:
  furnace_group_debug: true

modules:
  geo: DEBUG
  pam: INFO
  tm: INFO

function_overrides:
  calculate_unit_production_cost: WARNING
  extract_price_from_costcurve: ERROR

external:
  pyomo: ERROR
